VAR DEC IDX
VAR DEC PRD
DEF INT CTI ARR CHR VAL END
    VAR ARR CHR REM
    VAR DEC SUM
    VAR DEC SGN
    VAR DEC NEO
    SET SUM FAL
    SET NEO SUB ONE TWO
    IFT XOR ACC VAL FAL SUB SUB POW ADD SIX ONE TWO TWO TWO
        SET SGN ONE
        SET REM VAL
    ELS
        SET SGN NEO
        SET REM DEL VAL FAL
    END
    WHL LEN REM
        SET SUM ADD MUL SUM TEN ACC REM NEO
        SET REM DEL REM NEO
    END
    RET MUL SUM SGN
END
DEF ARR CHR ITC INT VAL END
    VAR ARR CHR OUT
    VAR INT REM
    VAR BOL NEG
    VAR DEC CHZ
    SET CHZ SUB POW ADD SIX ONE TWO ONE
    IFT VAL
        IFT AND VAL POW TWO SUB POW TWO SIX ONE
            SET NEG TRU
            SET REM MUL VAL SUB ONE TWO
        ELS
            SET NEG FLS
            SET REM VAL
        END
        WHL REM
            SET OUT INS OUT ADD MOD REM TEN CHZ FAL
            SET REM DIV REM TEN
        END
        IFT NEG
            RET INS OUT SUB SUB POW ADD SIX ONE TWO TWO TWO FAL
        ELS
            RET OUT
        END
    ELS
        RET ARR CHZ END
    END
END
SET IDX CTI GET
SET PRD ONE
WHL IDX
    SET PRD MUL PRD IDX
    SET IDX SUB IDX ONE
END
PUT ITC PRD