DEF INT CTI ARR CHR VAL END
    VAR ARR CHR REM
    VAR DEC SUM
    VAR DEC SGN
    VAR DEC NEO
    SET SUM FAL
    SET NEO SUB ONE TWO
    IFT XOR ACC VAL FAL SUB SUB POW ADD SIX ONE TWO TWO TWO
        SET SGN ONE
        SET REM VAL
    ELS
        SET SGN NEO
        SET REM DEL VAL FAL
    END
    WHL LEN REM
        SET SUM ADD MUL SUM TEN ACC REM NEO
        SET REM DEL REM NEO
    END
    RET MUL SUM SGN
END